baseURL = 'https://foxsociety-website.pages.dev'
languageCode = 'zh-CN'
title = '狐狸学社 | Fox Society'

[params]
description = '专业国际升学指导，点亮名校之路'
author = '狐狸学社'

[menu]
[[menu.main]]
name = '首页'
url = '/'
weight = 10
[[menu.main]]
name = '服务'
url = '/services/'
weight = 20
[[menu.main]]
name = '案例'
url = '/cases/'
weight = 30
[[menu.main]]
name = '关于'
url = '/about/'
weight = 40
[[menu.main]]
name = '联系'
url = '/contact/'
weight = 50
